set -x PATH $PATH .
set -x PATH $PATH $HOME/bin
set -x PATH $PATH /Users/krhodes/bin/git-scripts
set -x PATH $PATH /Applications
set -x PATH $PATH /Users/krhodes/.rvm/gems/ruby-2.1.2/bin
set -x PATH $PATH /Users/krhodes/.rvm/gems/ruby-2.1.2@global/bin
set -x PATH $PATH /Users/krhodes/.rvm/rubies/ruby-2.1.2/bin
set -x PATH $PATH /usr/local/opt/coreutils/libexec/gnubin
set -x PATH $PATH /usr/local/rvm/bin
set -x PATH $PATH /usr/local/bin
set -x PATH $PATH /usr/local/bin
set -x PATH $PATH /usr/bin
set -x PATH $PATH /bin
set -x PATH $PATH /usr/sbin
set -x PATH $PATH /sbin
set -x PATH $PATH /usr/local/munki
set -x PATH $PATH /Users/krhodes/Applications
set -x PATH $PATH /Users/krhodes/Applications/bin
set -x PATH $PATH /Users/krhodes/workspace/git-status-report
set -x PATH $PATH /Users/krhodes/workspace/git_accessories
set -x PATH $PATH /usr/local/git/bin
set -x PATH $PATH /Users/krhodes/.gem/ruby/1.8/bin
set -x PATH $PATH /Users/krhodes/gocode/bin
set -x PATH $PATH /Users/krhodes/workspace/gocode/bin
set -x PATH $PATH /Users/krhodes/.rvm/bin
set -x PATH $PATH /Users/krhodes/brew/bin
set -x PATH $PATH /Users/krhodes/brew/sbin
set -x PATH $PATH /Users/krhodes/workspace/useful_scripts/bin
set -x PATH $PATH /usr/local/heroku/bin
