(deftheme masukomi-style "my custom theme")
(custom-theme-set-faces
  'masukomi-style
  '(default ((t (:foreground "#eeeeec" :background "#272421"))))
  '(cursor ((t (:background "#fce94f"))))
  '(fringe ((t (:background "#1a1a1a"))))
  '(mode-line ((t (:foreground "#eeeeec" :background "#000000"))))
  '(region ((t (:background "#516911"))))
  '(font-lock-builtin-face ((t (:foreground "#53d22d"))))
  '(font-lock-comment-face ((t (:foreground "#e28c28"))))
  '(font-lock-function-name-face ((t (:foreground "#edd400"))))
  '(font-lock-keyword-face ((t (:foreground "#e25a63"))))
  '(font-lock-string-face ((t (:foreground "#9296dd"))))
  '(font-lock-type-face ((t (:foreground"#e2c334"))))
  '(font-lock-constant-face ((t (:foreground "#e8b95e"))))
  '(font-lock-variable-name-face ((t (:foreground "#dbd3b8"))))
  '(minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
  '(font-lock-warning-face ((t (:foreground "red" :bold t))))
)
(provide-theme 'masukomi-style)
